# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jhwdPuVa4VWuBndBse82Eqx7aX6e6Wr3
"""

import os
os.environ["WANDB_DISABLED"] = "true"

# !pip install pyarabic
# !pip install emoji
# !pip install transformers
# !pip install optuna
# !pip install torch
# !pip install nltk
# !pip install pyStemmer

# train_model.py (Enhanced for accuracy: MARBERTv2, tuned args, stratified split)
import numpy as np
import pandas as pd
import pyarabic.araby as ar
import re, emoji, Stemmer, string, random, gc
import torch, optuna
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.utils import resample
from sklearn.metrics import classification_report, accuracy_score, f1_score, precision_score, recall_score
from transformers import (
    AutoConfig,
    AutoModelForSequenceClassification,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback
)
from transformers.trainer_utils import EvaluationStrategy
from torch.utils.data import Dataset
import logging
import argparse

# Set up logging
logging.basicConfig(level=logging.WARNING)
logger = logging.getLogger(__name__)

# Constants
Tweets_Ids_Col_Train = "Tweet_id"
Tweets_Text_Col_Train = "Text"
Tweets_Sentiment_Col_Train = "sentiment"
Train_Data_File = 'default_train.csv'
Train_Data_Extended_File = "train_all_ext.csv"
Use_Train_Extended_Data = True
Rand_Seed = 42
Test_Size = 0.2  # changed from 0.001 to 0.2
Model_Used = "UBC-NLP/MARBERTv2"
Max_Len = 124

class BERTModelDataset(Dataset):
    def __init__(self, text, target, model_name, max_len, label_map):
        super().__init__()
        self.text = text
        self.target = target
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.max_len = max_len
        self.label_map = label_map

    def __len__(self):
        return len(self.text)

    def __getitem__(self, item):
        text = str(self.text[item])
        text = " ".join(text.split())
        encoded = self.tokenizer.encode_plus(
            text,
            max_length=self.max_len,
            add_special_tokens=True,
            return_token_type_ids=False,
            padding='max_length',
            truncation='longest_first',
            return_attention_mask=True,
            return_tensors='pt'
        )
        return {
            'input_ids': encoded['input_ids'].flatten(),
            'attention_mask': encoded['attention_mask'].flatten(),
            'labels': torch.tensor(self.label_map[self.target[item]], dtype=torch.long)
        }

# Text cleaning function
st = Stemmer.Stemmer('arabic')

def data_cleaning(text):
    text = re.sub(r'^https?://.*[\r\n]*', '', text, flags=re.MULTILINE)
    text = re.sub(r'http?://.*', '', text)
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"https\S+", "", text)
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r"(\s\d+)", "", text)
    text = re.sub(r"\d+", " ", text)
    text = ar.strip_tashkeel(text)
    text = ar.strip_tatweel(text)
    text = text.replace("#", " ").replace("@", " ").replace("_", " ")
    translator = str.maketrans('', '', string.punctuation)
    text = text.translate(translator)
    text = emoji.demojize(text, delimiters=(" ", " "))
    text = re.sub(r'(.)\1+', r'\1', text)
    text = " ".join([st.stemWord(i) for i in text.split()])
    text = text.replace("آ", "ا").replace("إ", "ا").replace("أ", "ا").replace("ؤ", "و").replace("ئ", "ي")
    return text

def compute_metrics(p):
    preds = np.argmax(p.predictions, axis=1)
    print(classification_report(p.label_ids, preds))
    return {
        'accuracy': accuracy_score(p.label_ids, preds),
        'macro_f1': f1_score(p.label_ids, preds, average='macro'),
        'macro_precision': precision_score(p.label_ids, preds, average='macro'),
        'macro_recall': recall_score(p.label_ids, preds, average='macro')
    }


def set_seed(seed):
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    np.random.seed(seed)
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)

class WeightedLossTrainer(Trainer):
    def __init__(self, weights, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = weights

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None): # Add num_items_in_batch argument
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits
        loss_fct = torch.nn.CrossEntropyLoss(weight=self.class_weights.to(logits.device))
        loss = loss_fct(logits, labels)
        return (loss, outputs) if return_outputs else loss


def model_init(label_map):
    return AutoModelForSequenceClassification.from_pretrained(
        Model_Used,
        return_dict=True,
        num_labels=len(label_map),
        force_download=True
    )

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--skip-training', action='store_true', help='Skip the training step if set')
    # The error was caused by the script expecting a command-line argument but not being provided
    # The following line parses the command-line arguments passed to the script.
    # If no arguments are provided, it uses default values. This line fixes the error.
    args = parser.parse_args(args=[])

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"⚠️ GPU Recognized. Running on: {device}")

    # Load and clean data
    data_file = Train_Data_Extended_File if Use_Train_Extended_Data else Train_Data_File
    train_data = pd.read_csv(data_file)
    train_data[Tweets_Text_Col_Train] = train_data[Tweets_Text_Col_Train].apply(data_cleaning)
    if Tweets_Ids_Col_Train in train_data.columns:
        train_data.drop(columns=[Tweets_Ids_Col_Train], inplace=True)
    train_data.columns = [Tweets_Sentiment_Col_Train, Tweets_Text_Col_Train]

    # Split
    train_set, eval_set = train_test_split(
        train_data,
        test_size=Test_Size,
        random_state=Rand_Seed,
        stratify=train_data[Tweets_Sentiment_Col_Train]
    )

    # Prepare label map and weights
    label_list = sorted(train_set[Tweets_Sentiment_Col_Train].unique())
    label_map = {v: i for i, v in enumerate(label_list)}
    print("Label map:", label_map)
    y_train = [label_map[x] for x in train_set[Tweets_Sentiment_Col_Train]]
    class_weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
    weights_tensor = torch.tensor(class_weights, dtype=torch.float).to(device)

    # Tokenizer
    tokenizer = AutoTokenizer.from_pretrained(Model_Used)

    # Datasets
    train_dataset = BERTModelDataset(
        train_set[Tweets_Text_Col_Train].tolist(),
        train_set[Tweets_Sentiment_Col_Train].tolist(),
        Model_Used,
        Max_Len,
        label_map
    )
    eval_dataset = BERTModelDataset(
        eval_set[Tweets_Text_Col_Train].tolist(),
        eval_set[Tweets_Sentiment_Col_Train].tolist(),
        Model_Used,
        Max_Len,
        label_map
    )

    # Training args
    training_args = TrainingArguments(
        output_dir="./train",
        learning_rate=5e-6,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        num_train_epochs=2,
        warmup_steps=100,
        weight_decay=0.01,
        logging_dir="./logs",
        logging_steps=100,
        eval_strategy='epoch',
        save_strategy='epoch',
        load_best_model_at_end=True,
        metric_for_best_model='accuracy',
        greater_is_better=True,
        seed=Rand_Seed,
        report_to='none',
        fp16=torch.cuda.is_available()
    )
    training_args.dataloader_pin_memory = False

    set_seed(Rand_Seed)
    gc.collect()
    torch.cuda.empty_cache()

    # Initialize Trainer
    trainer = WeightedLossTrainer(
        weights=weights_tensor,
        model_init=lambda: model_init(label_map),
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
    )

    # Training or skip
    if args.skip_training:
        print("⚠️ Skipping training as requested.")
    else:
        print("Starting training...")
        trainer.train()
        # Save model and tokenizer
        trainer.save_model("./saved_model")
        tokenizer.save_pretrained("./saved_model")
        print("Training complete. Model and tokenizer saved to ./saved_model")

    # Evaluation on the held-out test set
    print("Evaluating the best model on the test set...")
    metrics = trainer.evaluate(eval_dataset=eval_dataset)
    print("Evaluation results:", metrics)

if __name__ == "__main__":
    main()